name: Update TryHackMe Badge
on:
  schedule:
    - cron: '0 0 * * *' # Daily update
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch TryHackMe Badge
        uses: geeekgod/tryhackme-badge-action@v1.0
        with:
          username: 'YOUR_TRYHACKME_USERNAME'
          user_id: 'YOUR_TRYHACKME_USER_ID'
          image_path: './assets/tryhackme-badge.png'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
